import { createHash, createHmac, randomUUID } from 'node:crypto'
import { access, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { execFile as nodeExecFile } from 'node:child_process'
import { promisify } from 'node:util'
import type { DatabaseSync } from 'node:sqlite'
import type { Config } from './config.ts'

const execFile = promisify(nodeExecFile)
type Data = Record<string, unknown>
type AssetRow = { id: string, project_id: string, path: string, meta: string }

/** Local processing cache with OSS as the durable project and media store. */
export class VideoWorkspace {
  private db: DatabaseSync | undefined
  constructor(private readonly config: Config) {}
  private async open(): Promise<DatabaseSync> {
    if (this.db) return this.db
    await mkdir(this.config.dataDir, { recursive: true, mode: 0o700 })
    const { DatabaseSync } = await import('node:sqlite')
    const db = new DatabaseSync(join(this.config.dataDir, 'video-tools.sqlite'))
    db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL); CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,path TEXT NOT NULL,meta TEXT NOT NULL); CREATE TABLE IF NOT EXISTS analyses(asset_id TEXT PRIMARY KEY,data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS timelines(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,asset_id TEXT NOT NULL,start_us INTEGER NOT NULL,end_us INTEGER NOT NULL,revision INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL,status TEXT NOT NULL,output TEXT,detail TEXT)')
    this.db = db
    await this.restore()
    return db
  }
  async createProject(id: string, name: string): Promise<Data> { const db = await this.open(); db.prepare('INSERT INTO projects VALUES (?,?)').run(id, name); await this.manifest(id); return { id, name } }
  async projects(): Promise<Data[]> { return (await this.open()).prepare('SELECT p.id,p.name,count(a.id) asset_count FROM projects p LEFT JOIN assets a ON a.project_id=p.id GROUP BY p.id').all() as Data[] }
  async import(projectId: string, path: string): Promise<Data> { await access(path); const source = resolve(path); const bytes = await readFile(source); const hash = createHash('sha256').update(bytes).digest('hex'); const meta = await this.probe(source); const id = `asset-${hash.slice(0, 20)}`; const key = `${this.config.ossProjectPrefix.replace(/\/$/,'')}/${projectId}/assets/${id}/source${extname(source) || '.mp4'}`; await this.uploadBytes(bytes, key, 'video/mp4'); await rm(source, { force: true }); const db = await this.open(); db.prepare('INSERT OR REPLACE INTO assets VALUES (?,?,?,?)').run(id, projectId, `oss://${key}`, JSON.stringify({ ...meta, oss_key: key, source_name: basename(source), sha256: hash })); await this.manifest(projectId); return { id, project_id: projectId, path: `oss://${key}`, oss_key: key, ...meta } }
  async assets(projectId: string): Promise<Data[]> { const rows = (await this.open()).prepare('SELECT * FROM assets WHERE project_id=?').all(projectId) as AssetRow[]; return rows.map(row => ({ id: row.id, project_id: row.project_id, path: row.path, ...JSON.parse(row.meta) as Data })) }
  async understand(projectId: string, assetId: string, instruction: string | undefined, signal: AbortSignal): Promise<Data> { const asset = await this.asset(projectId, assetId); const source = await this.materialize(asset.path, signal); const file = await this.prepare(source.path, signal); const key = `${this.config.ossPrefix.replace(/\/$/,'')}/${projectId}/${assetId}/${randomUUID()}.mp4`; try { const url = await this.upload(file, key, 'video/mp4'); const data = await this.ask(url, `分析此视频并${instruction ?? '完整理解内容'}。只返回 JSON：{"summary":"","segments":[{"start_us":0,"end_us":1,"visual":"","audio":"","tags":[""],"highlight_reason":"","confidence":0.0}]}`, signal); const db = await this.open(); db.prepare('INSERT OR REPLACE INTO analyses VALUES (?,?)').run(assetId, JSON.stringify({ ...data, oss_key: key })); await this.manifest(projectId); return { asset_id: assetId, ...data } } finally { await rm(file, { force: true }); await source.cleanup() } }
  async search(projectId: string, query: string): Promise<Data[]> { const rows = (await this.open()).prepare('SELECT a.id,an.data FROM assets a JOIN analyses an ON an.asset_id=a.id WHERE a.project_id=?').all(projectId) as Array<{ id: string,data: string }>; const needle = query.toLowerCase(); return rows.flatMap(row => ((JSON.parse(row.data) as { segments?: Data[] }).segments ?? []).filter(segment => JSON.stringify(segment).toLowerCase().includes(needle)).map(segment => ({ asset_id: row.id, ...segment }))) }
  async find(projectId: string, assetId: string, subject: string, signal: AbortSignal): Promise<Data> { const asset = await this.asset(projectId, assetId); const source = await this.materialize(asset.path, signal); const file = await this.prepare(source.path, signal); const key = `${this.config.ossPrefix.replace(/\/$/,'')}/${projectId}/${assetId}/${randomUUID()}.mp4`; try { const result = await this.ask(await this.upload(file, key, 'video/mp4'), `找出“${subject}”的全部时间段。只返回 JSON：{"matches":[{"start_us":0,"end_us":1,"reason":"","confidence":0.0}]}`, signal); await this.manifest(projectId); return result } finally { await rm(file, { force: true }); await source.cleanup() } }
  async createTimeline(a: { id: string,project_id: string,asset_id: string,start_us: number,end_us: number }): Promise<Data> { if (a.end_us <= a.start_us) throw new Error('end_us must be after start_us'); (await this.open()).prepare('INSERT INTO timelines VALUES (?,?,?,?,?,1)').run(a.id,a.project_id,a.asset_id,a.start_us,a.end_us); await this.manifest(a.project_id); return { ...a, revision: 1 } }
  async timeline(id: string): Promise<Data> { const row = (await this.open()).prepare('SELECT * FROM timelines WHERE id=?').get(id) as Data | undefined; if (!row) throw new Error(`timeline not found: ${id}`); return row }
  async replaceTimeline(a: { timeline_id: string,base_revision: number,asset_id: string,start_us: number,end_us: number }): Promise<Data> { const old = await this.timeline(a.timeline_id) as { project_id: string,revision: number }; if (old.revision !== a.base_revision) throw new Error('revision conflict'); (await this.open()).prepare('UPDATE timelines SET asset_id=?,start_us=?,end_us=?,revision=? WHERE id=?').run(a.asset_id,a.start_us,a.end_us,a.base_revision + 1,a.timeline_id); await this.manifest(old.project_id); return this.timeline(a.timeline_id) }
  async render(timelineId: string, filename: string | undefined, signal: AbortSignal): Promise<Data> { const timeline = await this.timeline(timelineId) as { project_id: string,asset_id: string,start_us: number,end_us: number }; const asset = await this.assetById(timeline.asset_id); const source = await this.materialize(asset.path, signal); const output = join(this.config.dataDir, 'tmp', `${randomUUID()}-${filename ?? `${timelineId}.mp4`}`); const id = `job-${randomUUID()}`; await mkdir(dirname(output), { recursive: true }); const db = await this.open(); db.prepare('INSERT INTO jobs VALUES (?,?,?,?,?)').run(id,timelineId,'running',`oss://${this.config.ossOutputPrefix}/${id}`, ''); try { await this.run('ffmpeg',['-nostdin','-y','-ss',String(timeline.start_us / 1e6),'-to',String(timeline.end_us / 1e6),'-i',source.path,'-c','copy',output],signal); const key = `${this.config.ossOutputPrefix.replace(/\/$/,'')}/${timeline.project_id}/${id}-${filename ?? `${timelineId}.mp4`}`; const oss_url = await this.upload(output, key, 'video/mp4'); db.prepare('UPDATE jobs SET status=?,output=? WHERE id=?').run('completed',`oss://${key}`,id); await this.manifest(timeline.project_id); return { id,status:'completed',output:`oss://${key}`,oss_key:key,oss_url } } catch (error) { db.prepare('UPDATE jobs SET status=?,detail=? WHERE id=?').run('failed',String(error),id); throw error } finally { await rm(output, { force: true }); await source.cleanup() } }
  async jobs(): Promise<Data[]> { return (await this.open()).prepare('SELECT * FROM jobs ORDER BY rowid DESC').all() as Data[] }
  private async asset(projectId: string, id: string): Promise<{ path: string }> { const row = (await this.open()).prepare('SELECT path FROM assets WHERE id=? AND project_id=?').get(id,projectId) as { path: string } | undefined; if (!row) throw new Error(`asset not found: ${id}`); return row }
  private async assetById(id: string): Promise<{ path: string }> { const row = (await this.open()).prepare('SELECT path FROM assets WHERE id=?').get(id) as { path: string } | undefined; if (!row) throw new Error(`asset not found: ${id}`); return row }
  private async probe(path: string): Promise<Data> { const { stdout } = await this.run('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_type,width,height,avg_frame_rate','-of','json',path]); const result = JSON.parse(stdout) as { format: { duration: string },streams: Array<{ codec_type: string,width?: number,height?: number,avg_frame_rate?: string }> }; const video = result.streams.find(stream => stream.codec_type === 'video'); return { duration_us: Math.round(Number(result.format.duration) * 1e6),width: video?.width ?? 0,height: video?.height ?? 0,fps: video?.avg_frame_rate ?? '0/1' } }
  private async prepare(path: string, signal: AbortSignal): Promise<string> { const file = join(this.config.dataDir,'tmp',`${randomUUID()}.mp4`); await mkdir(dirname(file),{recursive:true}); await this.run('ffmpeg',['-nostdin','-y','-i',path,'-vf','scale=-2:720:force_original_aspect_ratio=decrease,fps=1','-c:v','libx264','-preset','veryfast','-crf','25','-c:a','aac','-b:a','64k',file],signal); return file }
  private async materialize(ref: string, signal: AbortSignal): Promise<{ path: string,cleanup: () => Promise<void> }> { if (!ref.startsWith('oss://')) return { path: ref, cleanup: async () => undefined }; const key = ref.slice('oss://'.length); const path = join(this.config.dataDir,'tmp',`${randomUUID()}-${basename(key)}`); await mkdir(dirname(path),{recursive:true}); const response = await fetch(this.signedUrl(key), { signal }); if (!response.ok) throw new Error(`OSS download failed: ${response.status}`); await writeFile(path, Buffer.from(await response.arrayBuffer())); return { path, cleanup: () => rm(path, { force: true }) } }
  private credentials(): { id: string,secret: string } { const id = process.env[this.config.ossAccessKeyIdEnv]; const secret = process.env[this.config.ossAccessKeySecretEnv]; if (!id || !secret) throw new Error('OSS credentials are not configured'); return { id,secret } }
  private objectUrl(key: string): string { return `https://${this.config.ossBucket}.${this.config.ossEndpoint.replace(/^https?:\/\//,'')}/${key.split('/').map(encodeURIComponent).join('/')}` }
  private signature(method: string,key: string,expires: string,contentType = ''): string { return createHmac('sha1',this.credentials().secret).update(`${method}\n\n${contentType}\n${expires}\n/${this.config.ossBucket}/${key}`).digest('base64') }
  private signedUrl(key: string): string { const expires = String(Math.floor(Date.now() / 1000) + this.config.signedUrlSeconds); return `${this.objectUrl(key)}?OSSAccessKeyId=${encodeURIComponent(this.credentials().id)}&Expires=${expires}&Signature=${encodeURIComponent(this.signature('GET',key,expires))}` }
  private async upload(path: string,key: string,contentType: string): Promise<string> { return this.uploadBytes(await readFile(path), key, contentType) }
  private async uploadBytes(data: Buffer, key: string, contentType: string): Promise<string> { const date = new Date().toUTCString(); const credentials = this.credentials(); const response = await fetch(this.objectUrl(key),{method:'PUT',headers:{Date:date,'Content-Type':contentType,Authorization:`OSS ${credentials.id}:${this.signature('PUT',key,date,contentType)}`},body:data as unknown as BodyInit}); if (!response.ok) { const detail = (await response.text()).trim().replace(/\s+/g, ' ').slice(0, 500); throw new Error(`OSS upload failed: ${response.status}${detail === '' ? '' : ` ${detail}`}`) } return this.signedUrl(key) }
  private async ask(url: string,prompt: string,signal: AbortSignal): Promise<Data> { const key = process.env[this.config.apiKeyEnv]; if (!key) throw new Error(`model API key is missing: ${this.config.apiKeyEnv}`); const response = await fetch(`${this.config.modelBaseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:this.config.model,temperature:0,messages:[{role:'user',content:[{type:'video_url',video_url:{url}},{type:'text',text:prompt}]}]})}); if (!response.ok) throw new Error(`Omni request failed: ${response.status} ${await response.text()}`); const body = await response.json() as { choices?: Array<{ message?: { content?: string } }> }; const text = body.choices?.[0]?.message?.content; const match = text?.match(/\{[\s\S]*\}/); if (!match) throw new Error('Omni did not return JSON'); return JSON.parse(match[0]) as Data }
  private async manifest(projectId: string): Promise<void> { const db = await this.open(); const project = db.prepare('SELECT * FROM projects WHERE id=?').get(projectId) as Data | undefined; if (!project) return; const assets = db.prepare('SELECT * FROM assets WHERE project_id=?').all(projectId); const timelines = db.prepare('SELECT * FROM timelines WHERE project_id=?').all(projectId); const jobs = db.prepare('SELECT j.* FROM jobs j JOIN timelines t ON t.id=j.timeline_id WHERE t.project_id=?').all(projectId); const analyses = db.prepare('SELECT a.id asset_id,an.data FROM assets a JOIN analyses an ON an.asset_id=a.id WHERE a.project_id=?').all(projectId); const prefix = this.config.ossProjectPrefix.replace(/\/$/,''); const key = `${prefix}/${projectId}/manifest.json`; await this.uploadBytes(Buffer.from(JSON.stringify({ version: 1, project, assets, timelines, jobs, analyses }, null, 2)), key, 'application/json'); const ids = (db.prepare('SELECT id FROM projects ORDER BY id').all() as Array<{ id: string }>).map(row => row.id); await this.uploadBytes(Buffer.from(JSON.stringify({ version: 1, projects: ids }, null, 2)), `${prefix}/index.json`, 'application/json') }
  private async restore(): Promise<void> { const db = this.db; if (!db || (db.prepare('SELECT count(*) count FROM projects').get() as { count: number }).count > 0) return; try { const indexResponse = await fetch(this.signedUrl(`${this.config.ossProjectPrefix.replace(/\/$/,'')}/index.json`)); if (!indexResponse.ok) return; const index = await indexResponse.json() as { projects?: string[] }; for (const id of index.projects ?? []) { const response = await fetch(this.signedUrl(`${this.config.ossProjectPrefix.replace(/\/$/,'')}/${id}/manifest.json`)); if (!response.ok) continue; const manifest = await response.json() as { project: { id: string, name: string }, assets?: Array<{ id: string, project_id: string, path: string, meta: string }>, timelines?: Array<Record<string, any>>, jobs?: Array<Record<string, any>>, analyses?: Array<{ asset_id: string, data: string }> }; db.prepare('INSERT OR IGNORE INTO projects VALUES (?,?)').run(manifest.project.id, manifest.project.name); for (const row of manifest.assets ?? []) db.prepare('INSERT OR IGNORE INTO assets VALUES (?,?,?,?)').run(row.id, row.project_id, row.path, row.meta); for (const row of manifest.timelines ?? []) db.prepare('INSERT OR IGNORE INTO timelines VALUES (?,?,?,?,?,?)').run(row.id, row.project_id, row.asset_id, row.start_us, row.end_us, row.revision); for (const row of manifest.jobs ?? []) db.prepare('INSERT OR IGNORE INTO jobs VALUES (?,?,?,?,?)').run(row.id, row.timeline_id, row.status, row.output, row.detail); for (const row of manifest.analyses ?? []) db.prepare('INSERT OR IGNORE INTO analyses VALUES (?,?)').run(row.asset_id, row.data) } } catch { /* OSS restore is best effort; normal local startup still works. */ } }
  private async run(file: string,args: string[],signal?: AbortSignal): Promise<{ stdout: string }> { const { stdout } = await execFile(file,args,{signal,maxBuffer:16 * 1024 * 1024}); return { stdout } }
}
